branches:
    only:
        - master

language: python
python:
    - 2.7

compiler:
    - g++
before_install:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
    - sudo apt-get -qq update
    - sudo apt-get install -y libboost-all-dev gfortran liblapack-dev libfftw3-dev python-dev python-numpy python-scipy python-nose
    - pushd $HOME
    #Only get TMV if not cached
    - if ! test -d tmv-0.73 || ! test -f tmv-0.73/Sconstruct; then wget https://github.com/rmjarvis/tmv/archive/v0.73.tar.gz && tar -xf v0.73.tar.gz ; else echo Using cached TMV; fi
    #But always install it to /usr/local
    - cd tmv-0.73 && sudo scons install DEBUG=True FLAGS="-O0"
    - popd

cache:
    pip: true
    directories:
    - $HOME/tmv-0.73

install:
    - pip install astropy==1.1.1 pyyaml future
    - scons
    - scons install

script:
    - cd tests
    # Use this rather than scons tests, so we can get the coverage options.
    - "nosetests test*.py --with-coverage --cover-package=galsim --with-doctest --cover-erase"
    # Without cover-erase, this will append to the .coverage file
    - "nosetests run_examples.py --with-coverage --cover-package=galsim --with-doctest"

after_success:
    # If we start doing multiple python versions here, then only report coveralls for one of them.
    # Otherwise the reported results get weird.
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi

